########################
#   全新3.0版本         #
# Hukaijun@emicent.com #
########################
version = 3.0-Dev

##环境 dev:开发 pro:生产 test：测试
env_model = "pro"
## 组件可选值 emi_ai_aicall;emi_ai_freeswitch;emi_ai_oc;emi_ai_mysql;emi_ai_redis;emi_ai_nlp
server_list=emic-ai-aicall;emic-ai-freeswitch;emic-ai-outcallserver;emic-ai-mysql;emic-ai-redis
###【如果不在此服务器上的组件需要填写正确的IP地址】
#server.freeswitch.emic
freeswitch_server_host=127.0.0.1
#outcallserver.emic
outcall_server_host=127.0.0.1
#aicall.emic
aicall_server_host=127.0.0.1
#tts.emic
tts_server_host=127.0.0.1
#mysql.emic
mysql_server_host=127.0.0.1
#redis.emic
redis_server_host=127.0.0.1
#asr.emic
asr_server_host=127.0.0.1

#docker image version
version_aicall=latest
version_outcall_server=latest
version_freeswitch=r3.22.69851
version_nlp=latest
version_mysql=5.7.40
version_redis=latest
#elasticsearch 镜像
version_analysis-elasticsearch=7.6.2
#spring 服务镜像
version_ai-analysis=1.0.0-220309

#data version 用于初始化数据 根据版本来的 init版本的mysql
version_data=87810

#tts类型选择 可选为"a" or "b"
tts_type = "a"

#docker 启动模式 【建议别动】
host_system=linux
network_mode=host
restart_mode=unless-stopped

host_exp_ip=127.0.0.1
host_ip=127.0.0.1

# 本地日志存储目录 【建议别动】
host_logs_dir=/var/pbx/logs
# 动态运行时数据
host_data_dir=/var/pbx/data/
# 本地资源目录
host_res_dir=/var/pbx/upload
# cache
host_ttscache_dir=/var/pbx/upload/robot/tts_cached
# docker所在位置
host_docker_lib=/var/pbx/lib
#硬盘资源
host_disk_dir=/var/pbx/
#配置
conf_path=/etc/pbx
#crontab位置
crontab_path=/etc/pbx/crontab
#脚本位置
script_path=/etc/pbx/scripts
# 用户运行
run_uid=1000

#Redis[无需改动]
redis_port=16379
redis_passwd=greeisgood

#MySQL[无需改动]
mysql_port=13306
mysql_password=Sinicnet@123456
#mysql的数据表等资源的文件版本以及文件夹 一般与aicall版本同步,需要特别指定
mysql_data_version=V43.41.91667
mysql_lib_path=/var/pbx/lib/emic_mysql
#data_resource_path=/var/pbx/Emi_AI_Install_V2.2/service
mysql_config_path=/etc/pbx/emic_mysql

#ai_web
http_port=1171
https_port=1172
#定制化服务
# 工行: GonghangJoinService
# 电信: TelejoinService
join_service=""

#freeswitch
### MRCP地址 ###
### 此项需要手动填写 ###
mrcp_host=127.0.0.1
tts_host =127.0.0.1

#outcall_server
outcall_server_port=9009
freeswitch_port=7010
web_api_host=127.0.0.1

#nlp
nlp_port=5002

#tts 【建议别动】
#@MARK:下版本移除
tts_port=18100
#tts 线路数
tts_num=10
#tts type=1表示加密狗激活 type=2表示激活码激活
tts_type=1