[common]
#是否离线安装
IS_OFFLINE=0

[AI_WEB]
#版本镜像名称
#可以从版本邮件中获取确保正确
IMAGE_NAME="aicall"

TAG_NAME="r3.1_r2"

PROJECT_HTTP_PORT=80

PROJECT_HTTPS_PORT=443

MYSQL_HOST='rm-2ze4h4gd92r731iapeo.mysql.rds.aliyuncs.com'

MYSQL_PASSWORD="Sinicnet123456"

MYSQL_USER="emi_ai"

#绑定的MOUNT_URL
#需要提前配置，否则无法连接
#例如：172.17.214.17:/usr/share/freeswitch/sounds/en/us/callie
MOUNT_URL=""

OC_SERVER="127.0.0.1"
